version: 2
jobs:
  build:
     docker:
      - image: circleci/python:3.7.9-buster
     steps:
      - setup_remote_docker
      - checkout
      - run:
          name: build_and_push
          command: |
            pip install -r requirements.txt
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            python build-push.py
workflows:
   version: 2
   build-publish-all:
      jobs:
         - build:
            context: dockerhub-publish
            filters:
               branches:
                  only: master
